### ISSUE TITLE
How to solve this problem？

### ISSUE THREAD

**Issue by wsj970619** [mal-lang/enterpriseLang#13]
![image](https://user-images.githubusercontent.com/32978521/139523584-ae6168bf-f191-4a5f-95f0-f4a061fd51ca.png)

**Comment by WendyXiong** [comment]
Hi! Please use this repo instead: https://github.com/KTH-SSAS/enterpriseLang.

**Comment by wsj970619** [comment]
Thank you for your reply.

I have another question to ask you. How do I get aws_access_key_id and aws_secret_access_key in the following figure? I have asked this question "support@foreseeti.com" E-mail sent many requests, but did not get a response, so I want to ask you how to get access? Do you need other conditions ? Please

![image](https://user-images.githubusercontent.com/32978521/139535598-f39e63b4-b49c-4782-a7d7-ca0bb284c16a.png)

**Comment by WendyXiong** [comment]
For this, I think foreseeti (Email: support@foreseeti.com) is the right one to ask for a free securiCAD version for running simulations for research purposes.

**Comment by wsj970619** [comment]
Yes, I am to finish my paper。
Do you suggest that I state in my email that I am for research purposes?

**Comment by WendyXiong** [comment]
Yes please state that in your email. I am not sure when they are available, so please wait for their reply.

**Comment by wsj970619** [comment]
Thank you very much for taking the time to answer. I hope your life is going well. Thank you again。

**Comment by wsj970619** [comment]
Thank you very much for taking the time to answer. I hope your life is going well. Thank you again。

**Comment by WendyXiong** [comment]
Thank you! May I ask: are you a university student, and which college are you from?

**Comment by wsj970619** [comment]
I'm from China，Zhongyuan University of Technology
